name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKER_USERNAME: satyammaurya

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: docker-compose -f  Github_Actions/docker-compose.yml up -d