name: Deploy to Server

on:
  workflow_call:

jobs:
  deploy-server:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to Pro server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            mkdir -p devops

      - name: Copy the docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Github_Actions/docker-compose.yml"
          target: "~/devops/docker-compose.yml"

      - name: SSH to prod and run the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Running App...."
            sudo apt-get update && sudo apt-get install -y docker.io docker-compose
            sudo usermod -aG docker $USER && newgrp docker
            export DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
            export DOCKER_TAG=${{ github.event.workflow_run.head_sha }}
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin
            cd ~/devops && docker-compose down && docker-compose up -d --build --force-recreate