name: DevSecOps end to end Pipeline

on:
  push:
    branches:
      - main

jobs:
# full CI code
  Code-quality:
    uses: ./.github/workflows/code-quality.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml
  docker-lint:
    uses: ./.github/workflows/docker-lint.yml
  build-image:
    needs: [Code-quality, dependency-scan, secrets-scan, docker-lint]
    uses: ./.github/workflows/docker_build_push.yml
    secrets: inherit

  trivy-scan:
    needs: build-image
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit

# deploy to the server
    deploy-server:
     needs: [trivy-scan]
     uses: ./.github/workflows/deploy-server.yml
     secrets: inherit